### ISSUE TITLE
Error: cannot allocate vector of size 741.2 Gb

### ISSUE THREAD

**Issue by ccmullally** [beniaminogreen/cragg#2]
Hello,
I ran into the error above when trying to implement the Stock-Yogo test using your cragg package. I'm working with a data set of about 1.4 million observations, 28 IVs, and one endogenous variable (I'm assuming that for size distortion results it's ok to have one endogenous variable but let me know if this is a problem for the package). The offending code is below:

```
stock_yogo_test(
  ~factor(region) + factor(yob) + Race + SMSA + Married + Age + Age2,  #Controls
  ~educ,            #Treatments
  ~factor(birthqtr):factor(yob),   #Instruments
  B=.1,       #Maximum Allowable Size Distortion
  size_bias="size", #Calculate critical value for size distortions
  data = df
)
```
I'm happy to provide the data. They are the Angrist and Krueger "quarter of birth-returns to education" data, which I'm using to create a problem set. Thanks in advance.

**Comment by beniaminogreen** [comment]
Hi there, thanks for getting in touch and sorry you are having issues with the package. 

I don't know of any issues that would arise from having one endogenous variable and 28 instruments. 

My guess reading the description of your problem is that this error occurs when R has to calculate (t(Z)*Z,)^-1*t(Z) as part of the test (where Z is the 28x1,400,000 matrix of instruments). The resulting product would be a 1,400,000x1,400,000 matrix, and too big to fit in memory (this likely explains the insane 741 GB memory allocation request).  If this is indeed the problem then there is no quick fix, but I will have a look to see if the algorithm can be modified to be less memory intensive. 

This is just a guess as I wasn't able to find the dataset you reference by googling, but if you were to send me a link I would be more than happy to look into this further and confirm whether this is indeed the issue. 

Best, 
Ben

**Comment by ccmullally** [comment]
Here is a link to the data:
https://www.dropbox.com/s/7yp69ggcej0ux83/cleandata2.dta?dl=0
Thanks for looking into this. As far as I know your package is the only one
for the Anderson Rubin test in R, which is why I want to use it as a
teaching tool in the problem set I'm creating.
Conner

**Comment by beniaminogreen** [comment]
I have checked using the dataset and my suspicions were correct  - the issue pops up when R tries to create the residual-maker matrix, which  is too large to store in memory. This is a core part of the test, so there is no easy work-around that I can think of. 

Unfortunately, I think you will either have to run the test on a subset of the data, or use another test for weak-instruments.  If I find any way to fix this issue, I will add it to the package.

**Comment by ccmullally** [comment]
Thanks, I appreciate it. I know they aren't really comparable, but the
ivreg2 package in Stata seems to calculate the AR test with no problems as
part of its standard output.

**Comment by beniaminogreen** [comment]
Looked into this issue again this week. I still don't see a way to reduce the memory usage of the test - there is no way to cut out the computation of the large residual-maker matrices that are computed as an intermediate step.
